# This file contains configuration for golangci-lint
# See https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  tests: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  gocyclo:
    min-complexity: 15
  misspell:
    locale: US
  revive:
    rules:
      - name: exported
        severity: warning
      - name: unexported-return
        severity: error

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - goimports
    - revive
    - gocritic
    - misspell
    - gocyclo
    - gofmt

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
